### ISSUE TITLE
Install_litex throws errors when switch --user is not used

### ISSUE THREAD

**Issue by Peter-van-Tol** [Peter-van-Tol/LiteX-CNC#47]
Is there something special for installing on raspberry pi4 with bookworm?

litexcnc install_litex throws errors.

also when I do "pip3 install litexcnc[cli] it doesn't work

```
litexcnc install_litex
Traceback (most recent call last):
  File "/home/cnc/.local/bin/litexcnc", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/cnc/.local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cnc/.local/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/cnc/.local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cnc/.local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cnc/.local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cnc/.local/lib/python3.11/site-packages/litexcnc/cli/install_litex.py", line 21, in cli
    target = os.path.join(target, 'litex')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 76, in join
TypeError: expected str, bytes or os.PathLike object, not NoneType

```

EDIT:
solved...forgot to install it with '--user'

_Originally posted by @OJthe123 in https://github.com/Peter-van-Tol/LiteX-CNC/discussions/36#discussioncomment-7048131_

**Comment by Peter-van-Tol** [comment]
Solved in #47. Also added auto-detection of architecture and os for selecting the required toolchain.
